"""Reader copy drawn from system/systems.json stays in plain product words.

Two rules, each checked at the registry and at every file generated from it:

- No registry text says "operator". A reader meets the product, the user, or a
  named team, never the site's own process role.
- A typed relation key such as integrates-lane is data. Readers see the wording
  in scripts/relation-wording.mjs, and the key stays in data-relation.
"""

import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OPERATOR = re.compile(r"(?i)\boperators?\b")
GENERATED_BANNER = "<!-- Generated by scripts/render-system-pages.mjs. Do not edit. -->"
CODE_BACKED_MAPS = ("system-capability-map", "security-capability-map", "verification-capability-map")
WORDING_ROW = re.compile(r'^\s*"([a-z-]+)": \{ before: "([^"]+)", after: "([^"]*)" \},$', re.M)


def _registry() -> dict:
    return json.loads((ROOT / "system" / "systems.json").read_text(encoding="utf-8"))


def _strings(node, path="$"):
    if isinstance(node, dict):
        for key, value in node.items():
            yield from _strings(value, f"{path}.{key}")
    elif isinstance(node, list):
        for index, value in enumerate(node):
            yield from _strings(value, f"{path}[{index}]")
    elif isinstance(node, str):
        yield path, node


def _generated_pages() -> list[Path]:
    pages = []
    for path in sorted(ROOT.rglob("*.html")):
        parts = path.relative_to(ROOT).parts
        if parts[0] in {"home", "node_modules"} or parts[0].startswith("."):
            continue
        if GENERATED_BANNER in path.read_text(encoding="utf-8"):
            pages.append(path)
    return pages


def _wording() -> dict[str, tuple[str, str]]:
    source = (ROOT / "scripts" / "relation-wording.mjs").read_text(encoding="utf-8")
    return {key: (before, after) for key, before, after in WORDING_ROW.findall(source)}


def _text(markup: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", markup))).strip()


def test_registry_text_uses_no_operator_wording() -> None:
    hits = [f"{path}: {value}" for path, value in _strings(_registry()) if OPERATOR.search(value)]
    assert hits == []


def test_files_generated_from_the_registry_carry_no_operator_wording() -> None:
    derived = [
        ROOT / "system" / "systems.js",
        ROOT / "home" / "src" / "system-registry.ts",
        ROOT / "security-tools.json",
        *[ROOT / "figures" / f"{name}.{ext}" for name in CODE_BACKED_MAPS for ext in ("html", "json", "svg")],
        *_generated_pages(),
    ]
    assert len(_generated_pages()) >= 15
    offenders = {
        str(path.relative_to(ROOT)): OPERATOR.findall(path.read_text(encoding="utf-8"))
        for path in derived
        if OPERATOR.search(path.read_text(encoding="utf-8"))
    }
    assert offenders == {}


def test_route_summaries_copied_from_the_registry_carry_no_operator_wording() -> None:
    routes = (ROOT / "system" / "routes.js").read_text(encoding="utf-8")
    encoded = re.search(r'ROUTE_REGISTRY_JSON = ("(?:[^"\\]|\\.)*");', routes).group(1)
    registry = json.loads(json.loads(encoded))
    system_hrefs = {record["href"] for record in _registry()["systems"]}
    checked = 0
    for family in registry["families"]:
        for route in family["routes"]:
            if route["href"] in system_hrefs:
                checked += 1
                assert not OPERATOR.search(route.get("summary", "")), route["href"]
                assert not OPERATOR.search(route.get("searchText", "")), route["href"]
    assert checked >= 30


def test_every_relation_key_has_reader_wording() -> None:
    wording = _wording()
    keys = {relation["relation"] for relation in _registry()["relations"]}
    assert "integrates-lane" in keys
    assert keys <= set(wording), sorted(keys - set(wording))
    assert wording["integrates-lane"] == ("includes", "as a lane")
    for before, after in wording.values():
        assert "-" not in before + after
        assert not OPERATOR.search(before + after)


def test_record_pages_show_relation_wording_and_keep_the_key_as_data() -> None:
    registry = _registry()
    wording = _wording()
    by_id = {record["id"]: record for record in registry["systems"]}
    pages = {path.relative_to(ROOT).as_posix(): path.read_text(encoding="utf-8") for path in _generated_pages()}
    shown = 0
    for relation in registry["relations"]:
        before, after = wording[relation["relation"]]
        source, target = by_id[relation["source"]], by_id[relation["target"]]
        for record in (source, target):
            page = pages.get(record["href"].lstrip("/"))
            if page is None:
                continue
            items = re.findall(rf'<li data-relation="{relation["relation"]}">(.*?)</li>', page, re.S)
            sentence = " ".join(part for part in (source["name"], before, target["name"], after) if part)
            assert any(_text(item).startswith(sentence) for item in items), (record["href"], sentence)
            shown += 1
    assert shown >= 12
    for record in registry["systems"]:
        page = pages.get(record["href"].lstrip("/"))
        if page is None:
            continue
        involved = [r for r in registry["relations"] if record["id"] in (r["source"], r["target"])]
        assert page.count("<li data-relation=") == len(involved), record["href"]
    for name, page in pages.items():
        for key in wording:
            assert f"<span>{key.replace('-', ' ')}</span>" not in page, (name, key)


def test_relay_record_reads_the_lane_relation_in_plain_words() -> None:
    page = _text((ROOT / "systems" / "relay.html").read_text(encoding="utf-8"))
    assert "Flywheel includes Relay as a lane" in page
    assert "integrates lane" not in page


def test_capability_maps_use_the_same_relation_wording() -> None:
    wording = _wording()
    label = " ".join(part for part in wording["integrates-lane"] if part)
    page = (ROOT / "figures" / "system-capability-map.html").read_text(encoding="utf-8")
    companion = json.loads((ROOT / "figures" / "system-capability-map.json").read_text(encoding="utf-8"))
    lane_rows = re.findall(rf'<th scope="row">Flywheel</th><td>{re.escape(label)}</td>', page)
    lane_relations = [r for r in _registry()["relations"] if r["relation"] == "integrates-lane"]
    assert len(lane_rows) == len(lane_relations) == 11
    assert "configured lane" not in page
    assert "configured lane" not in json.dumps(companion)
