"""Advisory IDs and package names stay whole on narrow screens.

A browser may end a line after any hyphen, so GHSA-82fg-qprm-q5r7 or flywheel-relay
can split across two lines. Pages wrap each token in class="ident" and the .ident
rule keeps it whole unless its container is narrower than the token
(scripts/ident-tokens.mjs). tests/ident-narrow-reading.cjs checks the rendered
result at 320, 375 and 390 px; this module checks the markup and the rule.
"""

import json
import re
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED_BANNER = "<!-- Generated by scripts/render-system-pages.mjs. Do not edit. -->"
SKIP = {"head", "script", "style", "svg", "title", "textarea"}
VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr"}
IDENT_RULE = ".ident{display:inline-block;max-width:100%;overflow-wrap:anywhere;text-decoration:inherit}"
HAND_PAGES = (
    "security.html", "gather.html", "forum.html", "crucible.html", "chorus.html", "toolkit.html",
    "proof-surface.html", "index-graph.html", "articulate.html", "flywheel.html",
    "security-toolkit.html", "index.html",
)
CODE_BACKED_MAPS = ("system-capability-map", "security-capability-map", "verification-capability-map")
# Classes whose own rule already keeps their text on one line, so a token inside
# needs no span (test_nowrap_parents_still_keep_their_text_on_one_line pins this).
NOWRAP_PARENTS = {"built-stat"}


def _ident_source() -> str:
    module = (ROOT / "home" / "src" / "system-registry.ts").read_text(encoding="utf-8")
    return json.loads(re.search(r"export const IDENT_SOURCE = (\".*\");", module).group(1))


IDENT = re.compile(_ident_source())


OPENING = "([{“‘"
STRANDED_AFTER = re.compile(r"[)\]}”’.,;:!?]+(?:\s|$)")


class _TextWalker(HTMLParser):
    """Collect text outside skipped elements, split by whether a whole-keeping element holds it.

    It also records punctuation that touches a marked element from outside: text that
    ends in an opening bracket right before one opens (other opening tags may sit
    between), and text that starts with closing punctuation right after one closes
    (other closing tags may sit between).
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.stack: list[tuple[str, bool, bool]] = []
        self.plain: list[str] = []
        self.marked: list[str] = []
        self.stranded: list[str] = []
        self._tail = ""
        self._after_ident = False

    def _in_ident(self) -> bool:
        return any(ident for _, _, ident in self.stack)

    def handle_starttag(self, tag, attrs):
        self._after_ident = False
        if tag in VOID:
            return
        classes = set((dict(attrs).get("class") or "").split())
        ident = "ident" in classes
        if ident and not self._in_ident() and self._tail[-1:] in set(OPENING):
            self.stranded.append(f"{self._tail[-12:]!r} before a marked token")
        self.stack.append((tag, bool(classes & ({"ident"} | NOWRAP_PARENTS)), ident))

    def handle_endtag(self, tag):
        self._tail = ""
        for index in range(len(self.stack) - 1, -1, -1):
            if self.stack[index][0] == tag:
                closed_ident = any(ident for _, _, ident in self.stack[index:])
                del self.stack[index:]
                if closed_ident and not self._in_ident():
                    self._after_ident = True
                return

    def handle_data(self, data):
        if any(tag in SKIP for tag, _, _ in self.stack):
            return
        if self._after_ident and STRANDED_AFTER.match(data):
            self.stranded.append(f"{data[:12]!r} after a marked token")
        self._after_ident = False
        self._tail = data
        (self.marked if any(keeps for _, keeps, _ in self.stack) else self.plain).append(data)


def _walk(path: Path) -> _TextWalker:
    walker = _TextWalker()
    walker.feed(path.read_text(encoding="utf-8"))
    return walker


def _marking_pages() -> list[Path]:
    generated = [
        path for path in sorted(ROOT.rglob("*.html"))
        if path.relative_to(ROOT).parts[0] not in {"home", "node_modules"}
        and not path.relative_to(ROOT).parts[0].startswith(".")
        and GENERATED_BANNER in path.read_text(encoding="utf-8")
    ]
    maps = [ROOT / "figures" / f"{name}.html" for name in CODE_BACKED_MAPS]
    return generated + maps + [ROOT / "site-index.html"] + [ROOT / page for page in HAND_PAGES]


def test_the_pattern_covers_every_package_and_advisory_the_registry_links() -> None:
    blob = json.dumps(json.loads((ROOT / "system" / "systems.json").read_text(encoding="utf-8"))["systems"])
    packages = {name for name in re.findall(r"pypi\.org/project/([a-z0-9-]+)/", blob) if "-" in name}
    advisories = set(re.findall(r"GHSA(?:-[a-z0-9]{4}){3}", blob))
    assert len(packages) >= 12 and len(advisories) >= 12
    for token in sorted(packages | advisories):
        match = IDENT.search(f" {token} ")
        assert match and match.group(2) == token, token
    assert "(?<" not in IDENT.pattern


def test_pages_leave_no_advisory_id_or_package_name_unmarked() -> None:
    marked_total = 0
    for path in _marking_pages():
        walker = _walk(path)
        loose = [m.group(2) for text in walker.plain for m in IDENT.finditer(text)]
        assert loose == [], f"{path.relative_to(ROOT)}: unmarked {loose[:5]}"
        marked_total += sum(1 for text in walker.marked if IDENT.search(f" {text} "))
    assert marked_total >= 150


def test_touching_punctuation_sits_inside_the_marked_token() -> None:
    # A marked token is an inline-block, and a line may break on either side of one. An
    # opening bracket just before it, or closing punctuation just after it, could then
    # end or start a line alone, so that punctuation belongs inside the marked element.
    checked = 0
    for path in _marking_pages():
        walker = _walk(path)
        checked += len(walker.marked)
        assert walker.stranded == [], f"{path.relative_to(ROOT)}: {walker.stranded[:3]}"
    assert checked >= 150


def test_nowrap_parents_still_keep_their_text_on_one_line() -> None:
    sheet = (ROOT / "system" / "system.css").read_text(encoding="utf-8")
    for name in NOWRAP_PARENTS:
        rule = re.search(rf"(?m)^\.{re.escape(name)}\{{([^}}]*)\}}", sheet)
        assert rule and "white-space:nowrap" in rule.group(1), name


def test_every_page_that_marks_a_token_links_a_sheet_with_the_ident_rule() -> None:
    checked = 0
    for path in sorted(ROOT.rglob("*.html")):
        parts = path.relative_to(ROOT).parts
        if parts[0] in {"home", "node_modules"} or parts[0].startswith("."):
            continue
        page = path.read_text(encoding="utf-8")
        if 'class="ident"' not in page:
            continue
        checked += 1
        sheets = [
            re.search(r'href="([^"?]+)', tag).group(1)
            for tag in re.findall(r"<link\b[^>]*>", page)
            if 'rel="stylesheet"' in tag
        ]
        rules = [
            (ROOT / sheet.lstrip("/") if sheet.startswith("/") else path.parent / sheet).read_text(encoding="utf-8")
            for sheet in sheets
        ]
        assert any(_has_ident_rule(rule) for rule in rules), path.relative_to(ROOT)
    assert checked >= 20


def _has_ident_rule(sheet: str) -> bool:
    # The hand sheets carry IDENT_RULE as written; the minified home sheet reorders it.
    block = re.search(r"\.ident\{([^}]*)\}", sheet)
    if not block:
        return False
    declarations = set(block.group(1).split(";"))
    return {"display:inline-block", "max-width:100%", "overflow-wrap:anywhere"} <= declarations


def test_the_ident_rule_never_lets_a_name_push_the_page_sideways() -> None:
    for sheet in ("system/system.css", "system/doc.css", "system/figure.css", "home/src/App.css"):
        assert IDENT_RULE in (ROOT / sheet).read_text(encoding="utf-8"), sheet
    # code inside a marked span takes no extra leading (a 3 px taller line otherwise)
    assert ".ident > code{line-height:1}" in (ROOT / "system" / "system.css").read_text(encoding="utf-8")
    figure = (ROOT / "system" / "figure.css").read_text(encoding="utf-8")
    # nowrap only where the table already scrolls inside its own box
    assert "@media screen { .figure-table-wrap .ident{white-space:nowrap} }" in figure
    assert re.search(r"\.figure-table-wrap \{[^}]*overflow-x: auto;", figure)
    for sheet in ("system/system.css", "system/doc.css", "home/src/App.css"):
        assert ".ident{white-space:nowrap}" not in (ROOT / sheet).read_text(encoding="utf-8")


def test_the_home_renders_registry_text_through_idents() -> None:
    app = (ROOT / "home" / "src" / "App.tsx").read_text(encoding="utf-8")
    for expression in ("evidence.label", "evidence.summary", "system.releaseState", "system.purpose",
                       "FLYWHEEL.entryCommand", "route.summary"):
        assert f"<Idents text={{{expression}}} />" in app, expression
    helper = (ROOT / "home" / "src" / "Idents.tsx").read_text(encoding="utf-8")
    assert "new RegExp(IDENT_SOURCE" in helper and 'className="ident"' in helper
    index = (ROOT / "index.html").read_text(encoding="utf-8")
    bundle = re.search(r'src="/assets/(index-[A-Za-z0-9_-]+\.js)"', index).group(1)
    css = re.search(r'href="/assets/(index-[A-Za-z0-9_-]+\.css)"', index).group(1)
    assert "GHSA(?:-[0-9a-z]{4}){3}" in (ROOT / "assets" / bundle).read_text(encoding="utf-8")
    styles = (ROOT / "assets" / css).read_text(encoding="utf-8")
    assert ".ident{" in styles and "display:inline-block" in styles and "max-width:100%" in styles
