"""Contracts for the generated v4 product overview route."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "overview.html"
SYSTEMS = ROOT / "system" / "systems.json"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def registry() -> dict[str, object]:
    return json.loads(read(SYSTEMS))


def systems_by_id() -> dict[str, dict]:
    return {record["id"]: record for record in registry()["systems"]}


def section(page: str, section_id: str) -> str:
    match = re.search(
        rf'<section\b[^>]*\bid="{re.escape(section_id)}"[^>]*>.*?</section>',
        page,
        re.DOTALL,
    )
    assert match, section_id
    return match.group(0)


def test_engines_page_is_the_generated_product_overview() -> None:
    page = read(PAGE)
    payload = registry()
    public_records = [
        record for record in payload["systems"] if record["maturity"] != "controlled-private"
    ]

    assert "<!-- Generated by scripts/render-system-pages.mjs. Do not edit. -->" in page
    assert "Zain Dana Harper" in page
    assert "Zentropy Labs" in page
    assert page.index("Zentropy Labs") < page.index("Flywheel")
    assert '<title>Products · Zentropy Labs</title>' in page
    assert '<body class="inner-clean frame-compact">' in page
    assert 'href="system/system.css?v=20260902-creative-chassis"' in page
    assert 'src="system/nav.js?v=20260902-creative-chassis"' in page
    assert "Products, grouped by primary domain." in page
    assert f"{len(public_records)} public product records across {len(payload['domains'])} domains." in page
    assert "Short map, detailed record elsewhere" in page
    assert 'href="catalog.html">evidence registry</a>' in page

    for domain in payload["domains"]:
        assert f'id="overview-{domain["id"]}"' in page
        assert f'href="#overview-{domain["id"]}"' in page

    for stale in (
        "Project Telos",
        "The fourteen engines",
        "Built as a field guide, not a funnel",
        'class="engine-rail"',
        'class="eyebrow"',
        'class="scenarios',
        'class="scenario',
    ):
        assert stale not in page


def test_engines_page_routes_to_products_evidence_and_work() -> None:
    page = read(PAGE)

    required_routes = (
        "flywheel.html",
        "systems/telos.html",
        "retro.html",
        "engine-revival.html",
        "brender-archival.html",
        "demonstrations.html",
        "analytics/portfolio-source-inventory.html",
        "private-practice.html#private-system-index",
        "catalog.html",
        "hire.html",
    )
    for route in required_routes:
        assert f'href="{route}"' in page, route

    for label in (
        "Flywheel",
        "Telos",
        "Retro Engine",
        "Engine Revival",
        "BRender Archival",
        "verified-inference platform and desktop client",
        "embedded browser visual and audiovisual studio",
        "archival/revival evidence platform",
        "BRender restoration and build-test harness",
    ):
        assert label in page


def test_engines_page_release_facts_match_the_system_registry() -> None:
    page = read(PAGE)
    systems = systems_by_id()

    for system_id in (
        "flywheel",
        "telos",
        "index",
        "gather",
        "forum",
        "crucible",
        "relay",
        "plexus",
        "mneme",
        "studio-engine",
        "retro-engine",
        "engine-revival",
        "brender-archival",
    ):
        record = systems[system_id]
        link = f'<a href="{record["href"]}">{record["name"]}</a>'
        primary = section(page, f'overview-{record["primaryDomain"]}')

        assert page.count(link) == 1, system_id
        assert link in primary, system_id
        assert record["productType"] in primary, system_id
        assert f'{record["maturity"]} · {record["releaseState"]}' in primary, system_id


def test_engines_page_keeps_readable_generated_overview_styles() -> None:
    page = read(PAGE)
    style = re.search(r"<style>(?P<body>.*?)</style>", page, re.DOTALL)
    assert style
    css = style.group("body")

    for selector in (
        ".system-hero",
        ".domain-nav",
        ".catalog-domain",
        ".catalog-count",
        ".system-family-nav",
    ):
        assert selector in css

    assert "@media(max-width:720px)" in css
    assert not re.search(r"font-size:\s*clamp\([^)]*,\s*[^,]+,\s*(?:[7-9]|\d{2,})rem", css)
