import { test } from "node:test";
import assert from "node:assert/strict";
import { navActive } from "./nav.js";

test("active section is derived from the path", () => {
  assert.equal(navActive("/"), "home");
  assert.equal(navActive("/index.html"), "home");
  assert.equal(navActive("/overview.html"), "flagships");
  assert.equal(navActive("/index-graph.html"), "flagships");
  assert.equal(navActive("/forum.html"), "flagships");
  assert.equal(navActive("/studio.html"), "flagships");
  assert.equal(navActive("/gather.html"), "flagships");
  assert.equal(navActive("/crucible.html"), "flagships");
  assert.equal(navActive("/catalog.html"), "catalog");
  assert.equal(navActive("/typeface.html"), "typeface");
  assert.equal(navActive("/demo-index.html"), "demos");
  assert.equal(navActive("/demonstrations.html"), "demos");
  assert.equal(navActive("/research.html"), "research");
  assert.equal(navActive("/research-proof-carrying-research-loops.html"), "research");
  assert.equal(navActive("/writing.html"), "writing");
  assert.equal(navActive("/the-summary-is-not-the-record.html"), "writing");
  assert.equal(navActive("/test-run-request.html"), "work");
  assert.equal(navActive("/why.html"), "research");
  assert.equal(navActive("/cv.html"), "about");
  assert.equal(navActive("/resume.html"), "work");
  assert.equal(navActive("/person.html"), "about");
  assert.equal(navActive("/cover-letter.html"), "work");
  assert.equal(navActive("/emet.html"), "catalog");
  assert.equal(navActive("/demo-emet.html"), "demos");
  assert.equal(navActive("/proof-surface-sample.html"), "demos");
  assert.equal(navActive("/quantalang.html"), "catalog");
  assert.equal(navActive("/atelier.html"), "catalog");
  assert.equal(navActive("/gallery.html"), "catalog");
});
