SHA = "bba8cce608f7c6155a9fd044f8b46d226d0aa04f"
B = f"https://github.com/HarperZ9/gather/blob/{SHA}/"
def L(path, label=None):
    return f'<a href="{B}{path}">{label or path}</a>'

PAGE = '<h1>Aperiodic monotile</h1> <p>The hat tile was announced in 2023 and tiles the plane with 1000 copies shown in the figure.</p> <p>Authors: Smith, Myers, Kaplan, Goodman-Strauss.</p>'
PILOT = ["manifest", "capture", "extract", "ground", "store", "receipt", "report", "re-check"]

SPEC = {
    "slug": "gather", "repo": "gather", "sha": SHA, "name": "gather", "version": "version 2.3.0",
    "description": "An animated walk through gather, research intake with receipts: page extraction with per-block hashes, a grounding check that rejects values not on the page, a content-addressed corpus that reports corrupt and missing bodies, and a digest that catches a tampered receipt. Built from gather at commit bba8cce.",
    "lede": "Pull research out of hard sources, and keep a receipt for every piece.",
    "for_you": "gather collects research from the places other tools break on: arXiv, authenticated APIs, JavaScript pages, scanned PDFs, audio, video, feeds and your own documents. Every block it extracts is bound to where it came from by a hash. A value a model proposes is kept only if it can be found on the page that was fetched. What you store can be re-hashed later, and anything changed or missing is named.",
    "uses": [
        ("Markdown with a receipt", "<code>gather extract</code> turns a page into Markdown and binds every block to its node path and content hash."),
        ("No ungrounded fields", "<code>verify_record</code> rejects a proposed value that appears nowhere on the fetched page, matched on word boundaries."),
        ("A corpus you can re-check", "Bodies are stored by hash and deduplicated. <code>gather corpus verify</code> reports CORRUPT and MISSING and exits non-zero."),
        ("Grants before reach", "A run that would start a command, use the network or send a credential needs a grant you set at launch."),
    ],
    "how_intro": "Scroll, or use the step buttons. The panel follows a short local page and two notes files through gather's own CLI and Python API, with no network. Every hash, count and verdict is output from gather at commit bba8cce.",
    "steps": [
        {"title": "Extract a page into blocks",
         "paras": ["Start with a small HTML page about the aperiodic monotile: a heading and two paragraphs. <code>gather extract article.html</code> parses it and returns one record per block.",
                   "Each block records its path in the document tree and a SHA-256 of its content. The whole record also carries hashes of the source and of the Markdown made from it."],
         "src": L("src/gather/extract.py") + "; README.md, \"Quickstart\"",
         "scene": [{"io": {"cmd": "gather extract article.html", "lines": [
             "html[1]/body[1]/h1[1]  h1  sha256 b09abb7b64e1424e...", "html[1]/body[1]/p[1]   p   sha256 1a8f9554b2960300...",
             "html[1]/body[1]/p[2]   p   sha256 95355aaf2715a43d...", ["content_sha256   4c907012d520ed44...", "hi"], ["markdown_sha256  94812767e4d6dd59...", "hi"],
             "method           html-extract"]}}]},
        {"title": "The Markdown it binds to",
         "paras": ["<code>gather markdown</code> prints the same extraction as plain Markdown, ready for a model's context. The hashes in the previous step let anyone check later that this text came from that page."],
         "src": "README.md, \"Features\"",
         "scene": [{"io": {"cmd": "gather markdown article.html", "lines": ["# Aperiodic monotile", "",
             "The hat tile was announced in 2023 and tiles the plane with 1000 copies shown in the figure.", "", "Authors: Smith, Myers, Kaplan, Goodman-Strauss."]}}]},
        {"title": "A proposed value must be on the page",
         "paras": ["Suppose a model extracts a record from the page. <code>verify_record</code> checks every value against the fetched content and marks each field grounded or not.",
                   "Matching is on word boundaries, so a claimed <code>100</code> does not match inside <code>1000</code>. A year the page never states is rejected too. Pick each record in the panel."],
         "src": L("src/gather/schema_extract.py") + ", <code>verify_record</code>",
         "scene": [{"cases": {"label": "Choose a proposed record", "items": [
             {"label": "copies 1000", "blocks": [{"table": {"head": ["field", "value", "grounded"], "rows": [["title", "Aperiodic monotile", "yes"], ["year", "2023", "yes"], ["copies", "1000", "yes"]]}},
                                                 {"verdict": ["all grounded", "ok", "every value is on the page"]}]},
             {"label": "copies 100", "blocks": [{"table": {"head": ["field", "value", "grounded"], "rows": [["title", "Aperiodic monotile", "yes"], ["year", "2023", "yes"], ["copies", "100", "no"]]}},
                                                {"verdict": ["rejected", "drift", "100 is not a word on the page; 1000 is"]}]},
             {"label": "year 2024", "blocks": [{"table": {"head": ["field", "value", "grounded"], "rows": [["title", "Aperiodic monotile", "yes"], ["year", "2024", "no"]]}},
                                               {"verdict": ["rejected", "drift", "the page says 2023"]}]}]}}]},
        {"title": "Store by content hash",
         "paras": ["Any fetch command takes <code>--store DIR</code>. Gathering two notes files writes each body under its own SHA-256, in <code>objects/75/24e3e0...</code> and <code>objects/77/a65127...</code>, and records them in a catalog.",
                   "Run the same command again and nothing new is written: both bodies are already there under the same hashes."],
         "src": "README.md, \"A durable local corpus\"; " + L("src/gather/store.py") + ", " + L("src/gather/corpus_cmd.py"),
         "scene": [{"io": {"cmd": "gather docs notes --store corpus", "lines": ["gathered 2 item(s)", "  document   monotile.md", "  document   rubik.md",
                                                                                "digest seal: 93971a3b1559c14b... | verified: True", ["stored to corpus: 2 added, 0 deduped", "hi"]]}},
                   {"io": {"cmd": "gather docs notes --store corpus", "lines": [["stored to corpus: 0 added, 2 deduped", "hi"]]}}]},
        {"title": "Re-check what you stored",
         "paras": ["<code>gather corpus verify</code> re-hashes every stored body and compares it with its address. Untouched, both read MATCH and it exits 0.",
                   "Change one word in a stored body and it reads CORRUPT. Delete a body and it reads MISSING. Either way the command exits 1. Pick each case in the panel."],
         "src": "README.md, \"Quickstart\"; " + L("src/gather/store.py") + ", " + L("src/gather/corpus_cmd.py"),
         "scene": [{"cases": {"label": "Choose a change", "items": [
             {"label": "nothing", "blocks": [{"io": {"cmd": "gather corpus verify corpus", "lines": ["verified 2 item(s): {'MATCH': 2}"], "verdict": ["exit 0", "ok", "every body re-hashes to its address"]}}]},
             {"label": "one word edited", "blocks": [{"io": {"cmd": "gather corpus verify corpus", "lines": ["verified 2 item(s): {'CORRUPT': 1, 'MATCH': 1}", ["  CORRUPT  monotile.md 7524e3e0d010", "hi"]], "verdict": ["exit 1", "drift", "the bytes no longer match their hash"]}}]},
             {"label": "and a body deleted", "blocks": [{"io": {"cmd": "gather corpus verify corpus", "lines": ["verified 2 item(s): {'CORRUPT': 1, 'MISSING': 1}", "  CORRUPT  monotile.md 7524e3e0d010", ["  MISSING  rubik.md 77a65127fc9f", "hi"]], "verdict": ["exit 1", "unv", "a missing body is named, never skipped"]}}]}]}}]},
        {"title": "A scope filter, and a sealed digest",
         "paras": ["<code>--scope monotile</code> keeps the items that mention the scope terms and counts what it dropped. The run ends with a digest: a seal over every item's receipt, verified on the spot."],
         "src": "README.md, \"Filter ledgers\"; " + L("src/gather/digest.py"),
         "scene": [{"io": {"cmd": "gather docs notes --scope monotile", "lines": [["gathered 1 item(s), dropped 1 out of scope", "hi"], "  document   monotile.md",
                                                                                   "digest seal: df1e36f2f44fa6aa... | verified: True"]}}]},
        {"title": "A tampered receipt breaks the digest",
         "paras": ["The bundled demo parses one video into three items, metadata, transcript and a comment, each with a receipt that verifies. It seals them into a digest, then edits one receipt. The digest no longer verifies."],
         "src": L("examples/demo.py"),
         "scene": [{"io": {"cmd": "python examples/demo.py", "lines": ["  metadata   abc123  sha256=40d9839ffb0e...  verify=True", "  transcript abc123  sha256=f798cd2c334c...  verify=True",
                                                                       "  comment    c1  sha256=301cf39d5091...  verify=True", "witnessed digest: 3 receipts, seal 7da7dc456b11..., verified True",
                                                                       ["after tampering one receipt, digest verifies: False  <- caught", "hi"]],
                           "verdict": ["verified False", "drift", "one edited receipt is enough"]}}]},
        {"title": "A pilot run puts it together",
         "paras": ["<code>gather pilot</code> takes a closed list of sources through capture, extraction, grounding and storage, then writes a redacted report and a hash-chained receipt. A source whose extracted values are not on the fetched page is recorded as an error and nothing from it is stored.",
                   "A third party re-checks the bundle with no network. This step is described from the README and docs/PILOT.md; a pilot fetches live sources, so it was not run for this page."],
         "src": "README.md, \"How a pilot run works\"; " + L("docs/PILOT.md"),
         "scene": [{"pipe": {"stages": PILOT, "active": 3, "note": "grounding drops a source before anything is stored"}},
                   {"cap": "Not run for this page: a pilot reaches the network."}]},
    ],
    "try": [
        ("Install from PyPI with <code>pip install gather-engine</code>, or from a checkout to run the demo (Python 3.11 or newer). None of this needs the network.",
         "$ git clone https://github.com/HarperZ9/gather && cd gather\n$ pip install -e .\n$ python examples/demo.py\n<span class=\"out\">witnessed digest: 3 receipts, seal 7da7dc456b11..., verified True\n\nafter tampering one receipt, digest verifies: False  <- caught</span>\n$ gather docs ./notes --store ./corpus\n$ gather corpus verify ./corpus"),
    ],
    "try_src": "Output from gather at bba8cce, run from source. gather-engine 2.3.0 is the current PyPI release.",
    "limits": [
        "A grounded value is one that appears on the fetched page. That shows the page says it. Whether the page is right is a separate check.",
        "Grounding is a word-boundary text match. A value written differently on the page, such as a number with a thousands separator, may read as ungrounded.",
        "Browser rendering, OCR, audio transcription and fast parsing are optional. <code>gather caps</code> reports which ones your install has.",
        "Corpus context selection is acquisition context. It makes no claim about truth, claim support or completeness.",
        "Video, Reddit and the scholarly APIs run under each service's terms and your own credentials.",
    ],
    "limits_src": "README.md at bba8cce, \"Current status\" and \"Features\"; src/gather/schema_extract.py",
    "recall": [
        ("Why is a proposed copies value of 100 rejected when the page says 1000?", "Grounding matches whole words, so 100 is not found inside 1000."),
        ("You run the same gather docs command twice with --store. What does the second run write?", "Nothing new. The bodies are stored under their own hashes, so both are deduplicated."),
        ("What is the difference between CORRUPT and MISSING in corpus verify?", "CORRUPT means the stored bytes no longer hash to their address. MISSING means the body is gone. Both make the command exit 1."),
        ("A pilot source's extracted fields are not on its fetched page. What is stored?", "Nothing from that source. It is recorded as an error."),
    ],
    "license_line": "gather is released under FSL-1.1-MIT.",
}
