SHA = "db3a8d4dba41786ee795621ade78d700eff6108e"
B = f"https://github.com/HarperZ9/mneme/blob/{SHA}/"
def L(path, label=None):
    return f'<a href="{B}{path}">{label or path}</a>'

TIERS = ["L0 turn", "L1 atom", "L2 scenario", "L3 persona"]
TURNS = ["user: My name is Alice and I live in Portland.", "user: I prefer tea over coffee and I work in data science.",
         ["assistant: Noted, Alice.", "dim"], "user: I am vegetarian and allergic to shellfish."]

SPEC = {
    "slug": "mneme", "repo": "mneme", "sha": SHA, "name": "mneme", "version": "release 0.7.0",
    "description": "An animated walk through mneme, accountable agent memory: facts stored with the turn they came from, recall with a receipt you can re-run, drift checks when a source changes, and erasure with an audit log. Built from mneme at commit db3a8d4.",
    "lede": "Agent memory where every recall can be re-run and every stale memory says so.",
    "for_you": "mneme gives an agent a memory you can question. Each stored fact names the turn it came from. Each recall returns a receipt with the scores and the rule that ranked it, which you can re-run to get the same ranking. When a source changes, the memory built on it reports drift. When you erase something, the erasure leaves an audit entry that says what went and holds none of the text.",
    "uses": [
        ("Facts with their source", "Every atomic fact records the turn it came from, the extractor, the criterion and a content hash."),
        ("Recall you can re-run", "<code>verify_recall</code> re-scores the store and confirms the ranking, so a tampered receipt fails."),
        ("Drift that reports itself", "A memory whose source changed reads DRIFT, and one whose source is gone reads UNVERIFIABLE."),
        ("Erasure you can audit", "<code>forget</code> removes a memory and the turns behind it, and leaves a hash-chained tombstone."),
    ],
    "how_intro": "Scroll, or use the step buttons. The panel follows one short conversation through mneme's own tour, <code>examples/tour.py</code>, which CI runs on every push. Every identifier, score and verdict is output from mneme at commit db3a8d4 with no model.",
    "steps": [
        {"title": "Four turns go in",
         "paras": ["Alice says three things about herself, and the assistant answers once. <code>remember</code> stores every turn verbatim as the bottom tier, L0.",
                   "Memory has four tiers. Raw turns sit at L0, atomic facts at L1, scene blocks at L2 and a persona at L3 that cites its facts."],
         "src": L("examples/tour.py") + ", <code>remember</code>; README.md, \"The 4-tier memory model\"",
         "scene": [{"pipe": {"stages": TIERS, "active": 0, "note": "L0 keeps the turns exactly as said"}},
                   {"io": {"cmd": 'mem.remember("alice", turns)', "lines": TURNS}}]},
        {"title": "Three facts come out, each with its source",
         "paras": ["The rule extractor turns the three user turns into three L1 facts. The assistant turn is context, not memory, so it yields none.",
                   "Each fact records the turn id it came from, the extractor <code>rule/v1</code>, the criterion and a SHA-256 of its content."],
         "src": L("src/mneme/memory.py") + ", <code>remember</code>; " + L("src/mneme/extract.py"),
         "scene": [{"pipe": {"stages": TIERS, "active": 1}},
                   {"table": {"head": ["fact", "text", "from turn"], "rows": [
                       ["98835a25", "My name is Alice and I live in Portland.", "7463dde3257d1778"],
                       ["04d7a310", "I prefer tea over coffee and I work in data science.", "d72bc7414c17f887"],
                       ["dffe9521", "I am vegetarian and allergic to shellfish.", "d9141c3271ddbb33"]]}},
                   {"verdict": ["3 atoms from 4 turns", "ink", "extractor rule/v1, criterion: atomic user fact"]}]},
        {"title": "Recall returns a receipt",
         "paras": ["Ask for \"tea or coffee preference\". The keyword recall scores each fact with BM25 and returns one hit at 1.783.",
                   "The receipt carries the query, the strategy, the fusion rule, the corpus size, every component score and a hash of the scorer's definition."],
         "src": L("src/mneme/recall.py") + ", <code>recall</code>",
         "scene": [{"io": {"cmd": 'mem.recall("tea or coffee preference", strategy="keyword")',
                           "lines": ['schema       mneme.recall/1', 'fusion       bm25', 'corpus_size  3',
                                     ['hit          04d7a310  bm25 1.7833  fused 1.7833', "hi"],
                                     '             "I prefer tea over coffee and I work in data science."',
                                     'def_sha256   a4aca2ec2ee49298...']}}]},
        {"title": "Re-run the recall to check it",
         "paras": ["<code>verify_recall</code> runs the same scorer over the same rows and compares the result with the receipt. It returns True.",
                   "Change a score inside the receipt and it returns False, because the ranking is re-derived and never read from the receipt. Change a stored fact and it returns False too, because the store no longer reproduces. Pick each case in the panel."],
         "src": L("src/mneme/recall.py") + ", <code>verify_recall</code>",
         "scene": [{"cases": {"label": "Choose what changed", "items": [
             {"label": "nothing", "blocks": [{"io": {"cmd": "verify_recall(receipt, rows)", "lines": ["True"], "verdict": ["reproduced", "ok", "same hits, same scores, same scorer hash"]}}]},
             {"label": "receipt score edited to 9.999", "blocks": [{"io": {"cmd": "verify_recall(edited_receipt, rows)", "lines": ["False"], "verdict": ["did not reproduce", "drift", "the scorer still gives 1.7833"]}}]},
             {"label": "stored fact edited", "blocks": [{"io": {"cmd": "verify_recall(receipt, rows_with_one_fact_changed)", "lines": ["False"], "verdict": ["did not reproduce", "drift", "the store no longer gives this ranking"]}}]}]}}]},
        {"title": "Drift: check every memory against its source",
         "paras": ["<code>drift</code> re-checks each memory. The row must first reproduce its own content hash. Then each cited source is re-hashed from its actual fields and compared with the hash taken at extraction.",
                   "On the fresh store all three facts read MATCH. Pick a change in the panel to see what each one does."],
         "src": L("src/mneme/drift.py") + "; README.md, \"A drift check for source changes\"",
         "scene": [{"cases": {"label": "Choose a change", "items": [
             {"label": "nothing", "blocks": [{"table": {"head": ["fact", "verdict"], "rows": [["98835a25", ["MATCH", "ok"]], ["04d7a310", ["MATCH", "ok"]], ["dffe9521", ["MATCH", "ok"]]]}},
                                            {"verdict": ["MATCH", "ok", "grounding present and unchanged"]}]},
             {"label": "source turn edited", "blocks": [{"table": {"head": ["fact", "verdict"], "rows": [["98835a25", ["DRIFT", "x"]], ["04d7a310", ["MATCH", "x"]], ["dffe9521", ["MATCH", "x"]]]}}, {"verdict": ["DRIFT", "drift", "98835a25: source content changed since extraction"]}]},
             {"label": "memory row edited", "blocks": [{"table": {"head": ["fact", "verdict"], "rows": [["98835a25", ["MATCH", "x"]], ["04d7a310", ["DRIFT", "x"]], ["dffe9521", ["MATCH", "x"]]]}}, {"verdict": ["DRIFT", "drift", "04d7a310: stored hash does not reproduce (memory row altered)"]}]},
             {"label": "source turn deleted", "blocks": [{"table": {"head": ["fact", "verdict"], "rows": [["98835a25", ["MATCH", "x"]], ["04d7a310", ["MATCH", "x"]], ["dffe9521", ["UNVERIFIABLE", "x"]]]}}, {"verdict": ["UNVERIFIABLE", "unv", "dffe9521: source(s) gone or unrecorded"]}]}]}}]},
        {"title": "The roll-up fails closed",
         "paras": ["Across a store, any DRIFT makes the whole report DRIFT. Otherwise any UNVERIFIABLE makes it UNVERIFIABLE. Only a clean sweep reports MATCH, and <code>mneme drift</code> exits 1 on drift.",
                   "A memory whose source was deleted is never rounded up to a match because nothing contradicted it. Missing evidence is reported as missing."],
         "src": "README.md, \"A drift check for source changes\"",
         "scene": [{"pipe": {"stages": ["any DRIFT?", "any UNVERIFIABLE?", "MATCH"], "active": 0, "note": "checked in this order; the first that applies is the report"}},
                   {"table": {"head": ["store holds", "report"], "rows": [
                       ["one DRIFT and one UNVERIFIABLE", ["DRIFT", "drift"]], ["one UNVERIFIABLE, rest MATCH", ["UNVERIFIABLE", "unv"]], ["all MATCH", ["MATCH", "ok"]]]}}]},
        {"title": "Forget, with a receipt",
         "paras": ["<code>forget</code> erases a memory, the turns it came from and everything derived from them, in one transaction. Other memories from the same turn need your consent.",
                   "Erasing the shellfish fact removed one memory row and one source turn. The receipt's status is <code>erased</code> with no findings, and the audit log holds two tombstones with its chain intact."],
         "src": L("src/mneme/erase.py") + ", <code>forget_memory</code>; README.md, \"Accountable forgetting\"",
         "scene": [{"io": {"cmd": 'mem.forget("dffe9521d4a4ccfb", reason="user requested deletion")',
                           "lines": ['status    erased', 'counts    turns 1, memories L1 1, collateral 0, duplicates 0', 'findings  []',
                                     ['audit     2 entries, chain_intact True', "hi"]],
                           "verdict": ["erased", "ok", "the fact is gone: memory(id) returns None"]}}]},
        {"title": "A tombstone holds no text",
         "paras": ["Each erased row leaves one audit entry with a random erase ref, the hash of the row before erasure, the reason and the entry's own hash, chained to the one before.",
                   "The entry stores a salted commitment to the erased text, and the salt is not stored, so the log cannot confirm a guess of what was erased."],
         "src": "README.md, \"Accountable forgetting\"; " + L("src/mneme/audit_writer.py"),
         "scene": [{"io": {"cmd": "mem.audit()['log'][0]",
                           "lines": ['op          erase', 'memory_id   er_00141410d02167acc72f7d5e', 'layer       L1',
                                     'before_sha  c45a259dfb0eeaa7...', 'after_sha   (empty)', 'reason      user requested deletion',
                                     ['entry_sha   62879caa0c3592df...', "hi"]]}}]},
    ],
    "try": [
        ("Install from PyPI (Python 3.11 or newer) or run the tour from a checkout. It needs no model and no network.",
         "$ python -m pip install flywheel-mneme\n$ git clone https://github.com/HarperZ9/mneme && cd mneme\n$ python examples/tour.py\n<span class=\"out\">== 2. recall &#8212; with a receipt a third party can re-run ==\n    [1.783] I prefer tea over coffee and I work in data science.\n  re-ran the scorer: identical ranking (the recall is re-derivable)\n\n== 3. drift &#8212; a memory whose source changes flags itself ==\n  before: MATCH\n  after a source changed: DRIFT (stale memory says so, it is not silently served)</span>"),
    ],
    "try_src": "Output excerpt from examples/tour.py at db3a8d4. flywheel-mneme 0.7.0 is the current release on PyPI.",
    "limits": [
        "The default extractor is rule-based. It picks fact-shaped sentences by cue words and does not understand them; an LLM extractor is optional and sends text to its provider.",
        "A recall receipt proves the ranking reproduces from the stored rows. It says nothing about whether the stored fact is true.",
        "Drift compares sources with what was recorded at extraction. It cannot tell you a source was wrong from the start.",
        "The check that a forget reason does not repeat erased text catches verbatim repeats only. A paraphrase passes.",
        "Text you send through an LLM extractor, an embedder or an MCP client goes to that provider under its terms. The store itself stays on your machine.",
    ],
    "limits_src": "README.md at db3a8d4, \"Install\", \"Accountability features\" and \"Accountable forgetting\"",
    "recall": [
        ("Why does the assistant's turn produce no fact?", "It is context. The extractor keeps atomic facts from the user's turns, so four turns give three facts."),
        ("A receipt's score is edited but its scorer hash is left alone. What does verify_recall return, and why?", "False. It re-runs the scorer over the rows and compares the ranking, so a matching hash cannot carry an edited score."),
        ("What is the difference between a source edited and a source deleted?", "An edited source re-hashes differently, so the memory reads DRIFT. A deleted source cannot be checked at all, so it reads UNVERIFIABLE."),
        ("A store has one MATCH, one DRIFT and one UNVERIFIABLE memory. What does the report say?", "DRIFT. Any drift wins, then any unverifiable, and MATCH only on a clean sweep."),
    ],
    "license_line": "mneme is released under FSL-1.1-MIT.",
}
