SHA = "510e84cdf1a8e58a3ca134e339e401d1dd9607e5"
B = f"https://github.com/HarperZ9/terminal-state-fixtures/blob/{SHA}/"
def L(path, label=None):
    return f'<a href="{B}{path}">{label or path}</a>'
ENV = "environments/mlflow_terminal_state/"

RULES = ["launched?", "timed out?", "provider refused?", "malformed?", "integrity broken?", "oracle absent?", "oracle pass or fail"]

SPEC = {
    "slug": "terminal-state-fixtures", "repo": "terminal-state-fixtures", "sha": SHA, "name": "terminal-state-fixtures", "version": "mlflow-terminal-state 0.1.1",
    "description": "An animated walk through terminal-state-fixtures, evaluation environments that score an AI agent by the state it left: five fields enumerated into 324 run records, an eight-rule reference scorer where integrity outranks the oracle, only 23 rows in the quality denominator, and rewards that pay for exclusions as well as verdicts. Built from terminal-state-fixtures at commit 510e84c.",
    "lede": "Score an AI agent by the state its work leaves behind.",
    "for_you": "A transcript says what a model believes happened; the terminal state says what happened. These environments score by the second. The first one teaches a model to sort agent-run records into seven terminal verdicts and to decide which runs belong in a quality denominator, so a provider outage or a blocked launch stops showing up as a fake regression. Every row is generated from a reference scorer, so every score can be re-derived.",
    "uses": [
        ("Exhaustive, not sampled", "Five fields with every reachable combination: 324 records."),
        ("Ground truth from a scorer", "The dataset is generated by a deterministic reference scorer written first."),
        ("Exclusions are scored", "One reward pays for the verdict and another for getting the denominator right."),
        ("Claims pinned as tests", "Exhaustiveness, rewards, and the integrity rule are all tests."),
    ],
    "how_intro": "Scroll, or use the step buttons. The panel runs the reference scorer and the two reward functions from <code>mlflow_terminal_state.py</code> at commit 510e84c, with stand-in modules in place of the verifiers and datasets packages, which the scorer itself does not need.",
    "steps": [
        {"title": "A run record has five fields",
         "paras": ["Each record describes one agent run on five axes: what the run did, how the provider answered, what the independent check said, whether the record's receipt is intact, and whether the artifact hashes recompute. Every combination is enumerated: 4 x 3 x 3 x 3 x 3 = 324 records, with no sampling."],
         "src": L(ENV + "mlflow_terminal_state.py") + ", <code>FIELDS</code> and <code>build_dataset</code>",
         "scene": [{"table": {"head": ["field", "values"], "rows": [["execution", "returned, timeout, blocked, unlaunched"], ["provider", "ok, rejected, malformed"], ["oracle", "pass, fail, absent"], ["receipt", "verified, mismatch, absent"], ["artifact", "match, mismatch, absent"]]}},
                   {"verdict": ["324 records", "ink", "every reachable combination"]}]},
        {"title": "Eight rules, in a fixed order",
         "paras": ["The reference scorer settles the states that must not count as failures first. A blocked or never-launched run is not a run. A timeout reached no answer. A structured provider refusal is not a task failure. Output that never parsed is not a claim. Then integrity: a receipt or artifact mismatch refutes the run even if the oracle passed. Only then does the oracle decide, and an absent oracle is an honest null."],
         "src": L(ENV + "mlflow_terminal_state.py") + ", <code>score</code>",
         "scene": [{"pipe": {"stages": RULES, "active": 4, "note": "checked left to right; the first rule that applies decides"}},
                   {"table": {"head": ["rule", "verdict", "in denominator"], "rows": [["blocked or unlaunched", "not_launched", "no"], ["timeout", "timeout", "no"], ["provider rejected", "rejected", "no"], ["provider malformed", "malformed", "no"],
                                                                                    ["receipt or artifact mismatch", "refuted", "yes"], ["oracle absent", "unverifiable", "no"], ["oracle pass", "verified", "yes"], ["oracle fail", "refuted", "yes"]]}}]},
        {"title": "Score some records",
         "paras": ["Pick a record in the panel. An oracle pass with a broken receipt is refuted, because integrity outranks the oracle. An oracle pass with nothing broken is verified. A run with no oracle is unverifiable and left out of the denominator, and so is a timeout, even one whose oracle failed."],
         "src": L(ENV + "mlflow_terminal_state.py") + ", <code>score</code>",
         "scene": [{"cases": {"label": "Choose a record", "items": [
             {"label": "pass, all intact", "blocks": [{"io": {"cmd": "returned / ok / oracle pass / receipt verified / artifact match", "lines": ["verdict verified, in_denominator true"], "verdict": ["verified", "ok"]}}]},
             {"label": "pass, receipt mismatch", "blocks": [{"io": {"cmd": "returned / ok / oracle pass / receipt mismatch / artifact match", "lines": ["verdict refuted, in_denominator true"], "verdict": ["refuted", "drift", "integrity beats the oracle"]}}]},
             {"label": "no oracle", "blocks": [{"io": {"cmd": "returned / ok / oracle absent / receipt verified / artifact match", "lines": ["verdict unverifiable, in_denominator false"], "verdict": ["unverifiable", "unv", "an honest null, not a pass"]}}]},
             {"label": "timeout, oracle fail", "blocks": [{"io": {"cmd": "timeout / ok / oracle fail / receipt verified / artifact match", "lines": ["verdict timeout, in_denominator false"], "verdict": ["excluded", "unv", "no terminal answer"]}}]},
             {"label": "provider refused", "blocks": [{"io": {"cmd": "returned / rejected / oracle fail / receipt absent / artifact absent", "lines": ["verdict rejected, in_denominator false"], "verdict": ["excluded", "unv", "a refusal is not a task failure"]}}]}]}}]},
        {"title": "Only 23 of 324 belong in the denominator",
         "paras": ["Across all 324 records, half are runs that never launched and a quarter timed out. Only verified and refuted runs count toward quality: 23 rows. Counting everything that did not pass as a failure would have put 320 rows in a failure column."],
         "src": L(ENV + "mlflow_terminal_state.py"),
         "scene": [{"table": {"head": ["verdict", "rows", "counts"], "rows": [["not_launched", "162", "no"], ["timeout", "81", "no"], ["rejected", "27", "no"], ["malformed", "27", "no"], ["refuted", "19", "yes"], ["unverifiable", "4", "no"], ["verified", "4", "yes"]]}},
                   {"verdict": ["23 in the denominator", "ok", "4 verified and 19 refuted"]}]},
        {"title": "Rewards pay for the exclusion too",
         "paras": ["A model answers with a JSON verdict and a denominator flag. The verdict is worth 0.7 and the denominator flag 0.3. For a record whose answer is refuted and counted, pick each model answer in the panel. Prose with no JSON scores 0."],
         "src": L(ENV + "mlflow_terminal_state.py") + ", <code>verdict_reward</code>, <code>denominator_reward</code> and <code>load_environment</code>",
         "scene": [{"cases": {"label": "Choose a model answer", "items": [
             {"label": "refuted, counted", "blocks": [{"io": {"lines": ['{"verdict": "refuted", "in_denominator": true}', "verdict 1.0 x 0.7 + denominator 1.0 x 0.3"], "verdict": ["1.0", "ok"]}}]},
             {"label": "verified, counted", "blocks": [{"io": {"lines": ['{"verdict": "verified", "in_denominator": true}', "verdict 0.0 x 0.7 + denominator 1.0 x 0.3"], "verdict": ["0.3", "drift"]}}]},
             {"label": "refuted, not counted", "blocks": [{"io": {"lines": ['{"verdict": "refuted", "in_denominator": false}', "verdict 1.0 x 0.7 + denominator 0.0 x 0.3"], "verdict": ["0.7", "drift"]}}]},
             {"label": "the run looks fine to me", "blocks": [{"io": {"lines": ["no JSON object found"], "verdict": ["0.0", "drift"]}}]}]}}]},
        {"title": "A second environment: write and repair components",
         "paras": ["verifiers-component-forge asks a model to write or repair parts of an evaluation environment against a written contract. Five families carry 337 cases and 5,058 frozen expectations, scored by running the model's code in a child process against hidden probes. Returning a broken module unchanged scores at most the frozen regression share.",
                   "This step is described from the README; its runs need the verifiers toolchain and a model."],
         "src": "README.md, \"verifiers-component-forge\"; " + L("environments/verifiers-component-forge/REPRODUCE.md"),
         "scene": [{"pipe": {"stages": ["contract", "model writes", "structural gate", "child process", "hidden probes", "reward"], "active": 4}},
                   {"cap": "Not run for this page: it needs the verifiers toolchain and a model."}]},
    ],
    "try": [
        ("Run the pinned claims for the first environment (uses uv and the verifiers package).",
         "$ git clone https://github.com/HarperZ9/terminal-state-fixtures && cd terminal-state-fixtures/environments/mlflow_terminal_state\n$ uv venv && uv pip install verifiers pytest\n$ uv run pytest tests/ -q"),
    ],
    "try_src": "The scorer and reward values above were computed from mlflow_terminal_state.py at 510e84c with stand-in modules for verifiers and datasets; the tests were not run for this page.",
    "limits": [
        "No scored model run is recorded for the first environment, so nothing here is evidence about how a model performs on it.",
        "Version 0.1.1 is staged privately on the Environments Hub; it is not a public Hub release.",
        "The environment teaches a fixed classification contract. Real run records may carry states the five fields do not cover.",
    ],
    "limits_src": "README.md at 510e84c, \"Environments\" and the fixture table",
    "recall": [
        ("An oracle passed but the receipt does not match. What is the verdict?", "Refuted, and it counts: integrity outranks the oracle."),
        ("How many of the 324 records belong in the quality denominator?", "23: the 4 verified and the 19 refuted."),
        ("A model gets the verdict right but the denominator wrong. What does it score?", "0.7."),
    ],
    "license_line": "terminal-state-fixtures is released under the MIT license.",
}
