"""Square icons for the flagship plugins: one aperture family, one motif per tool.

Every icon shares the same parts: the site's void ground, a hairline aperture
ring, fine bone line-work, and one incandescent core as the single hot mark. The
motif inside the ring tells the tools apart (tools/plugin_icon_art.py).

Three detail tiers keep the line-work legible at each export size:
  full  (512 px and up)  fine strokes, dense line-work, grain and scanlines
  mid   (128 and 256)    medium strokes, half the line count
  small (48 and 64)      heavy strokes, a few lines, no texture
plus a transparent glyph for composer chips, in ink (light UI) and bone (dark UI).
"""

from __future__ import annotations

import random
import zlib

from tools.plugin_icon_art import C, MOTIFS, R, f

GROUND = "#040308"
BONE = "#eae3f7"
INK = "#17181c"
CORE = "#fff3e2"
HALO = "#f3c88c"

TIERS = {
    "full": {"sw": 2.4, "core": 50, "rim": 7, "halo": 3.6, "texture": True},
    "mid": {"sw": 5.5, "core": 56, "rim": 11, "halo": 3.3, "texture": False},
    "small": {"sw": 15, "core": 74, "rim": 20, "halo": 2.4, "texture": False},
}
# Line counts per tool for the full, mid and small tiers.
COUNTS = {
    "articulate": (34, 18, 8), "canon": (16, 10, 5), "crucible": (132, 60, 18),
    "forum": (15, 8, 4), "gather": (44, 22, 9), "index": (16, 10, 5),
    "learn": (30, 18, 9), "mneme": (22, 11, 5), "plexus": (17, 11, 7),
    "relay": (15, 8, 4), "telos": (64, 36, 12),
}
PNG_SIZES = {48: "small", 64: "small", 128: "mid", 256: "mid", 512: "full", 1024: "full"}
GLYPH_PNG = 128


def seed_for(slug: str) -> int:
    return zlib.crc32(f"plugin-icon/{slug}".encode()) & 0x7FFFFFFF


def motif(slug: str, tier: str) -> list[str]:
    count = COUNTS[slug][("full", "mid", "small").index(tier)]
    return MOTIFS[slug](random.Random(seed_for(slug)), count)


def texture(slug: str) -> tuple[str, str]:
    defs = (f'<filter id="{slug}-grain" x="0" y="0" width="100%" height="100%">'
            f'<feTurbulence type="fractalNoise" baseFrequency="0.62" numOctaves="3" seed="{seed_for(slug) % 997}"/>'
            '<feColorMatrix values="0 0 0 0 0.92  0 0 0 0 0.89  0 0 0 0 0.97  1.6 0 0 0 -0.35"/>'
            '<feComponentTransfer><feFuncA type="discrete" tableValues="0 0 0 0 0 0 0 0.28"/>'
            '</feComponentTransfer></filter>'
            f'<pattern id="{slug}-scan" width="8" height="8" patternUnits="userSpaceOnUse">'
            f'<rect width="8" height="2" fill="{BONE}" opacity="0.035"/></pattern>')
    body = (f'<rect width="1024" height="1024" fill="url(#{slug}-scan)"/>'
            f'<rect width="1024" height="1024" filter="url(#{slug}-grain)"/>')
    return defs, body


def art_group(slug: str, tier: str, color: str, masked: bool = False) -> str:
    sw = TIERS[tier]["sw"]
    fill = color if slug == "learn" else "none"
    stroke = "none" if slug == "learn" else color
    shapes = "".join(motif(slug, tier))
    mask = f' mask="url(#{slug}-pupil)"' if masked else ""
    return (f'<g clip-path="url(#{slug}-ap)"{mask} fill="{fill}" stroke="{stroke}" stroke-width="{sw}" '
            f'stroke-linecap="round" stroke-linejoin="round">{shapes}</g>'
            f'<circle cx="{f(C)}" cy="{f(C)}" r="{f(R + 8)}" fill="none" stroke="{color}" '
            f'stroke-width="{f(sw * 0.8)}" opacity="0.42"/>')


def header(slug: str, label: str, what: str) -> str:
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024" '
            f'role="img" aria-label="{label} plugin icon">'
            f'<title>{label}</title><desc>{what} Generated by tools/build_plugin_support_pages.py, '
            f'seed {seed_for(slug)}.</desc>')


def clip(slug: str) -> str:
    return f'<clipPath id="{slug}-ap"><circle cx="{f(C)}" cy="{f(C)}" r="{f(R + 8)}"/></clipPath>'


def pupil(slug: str, radius: float) -> str:
    return (f'<mask id="{slug}-pupil"><rect width="1024" height="1024" fill="#fff"/>'
            f'<circle cx="{f(C)}" cy="{f(C)}" r="{f(radius)}" fill="#000"/></mask>')


def tile_svg(slug: str, label: str, tier: str) -> str:
    t = TIERS[tier]
    tex_defs, tex_body = texture(slug) if t["texture"] else ("", "")
    halo = (f'<radialGradient id="{slug}-halo"><stop offset="0" stop-color="{CORE}" stop-opacity="0.95"/>'
            f'<stop offset="0.32" stop-color="{HALO}" stop-opacity="0.42"/>'
            f'<stop offset="1" stop-color="{HALO}" stop-opacity="0"/></radialGradient>')
    core = (f'<circle cx="{f(C)}" cy="{f(C)}" r="{f(t["core"] * t["halo"])}" fill="url(#{slug}-halo)"/>'
            f'<circle cx="{f(C)}" cy="{f(C)}" r="{t["core"]}" fill="{GROUND}"/>'
            f'<circle cx="{f(C)}" cy="{f(C)}" r="{t["core"]}" fill="none" stroke="{CORE}" stroke-width="{t["rim"]}"/>')
    return (header(slug, label, f"{label} plugin icon, {tier} detail tier.")
            + f"<defs>{clip(slug)}{halo}{tex_defs}</defs>"
            + f'<rect width="1024" height="1024" fill="{GROUND}"/>'
            + art_group(slug, tier, BONE) + core + tex_body + "</svg>\n")


def glyph_svg(slug: str, label: str, dark: bool) -> str:
    color = BONE if dark else INK
    t = TIERS["small"]
    core = (f'<circle cx="{f(C)}" cy="{f(C)}" r="{t["core"]}" fill="none" stroke="{color}" '
            f'stroke-width="{t["rim"]}"/><circle cx="{f(C)}" cy="{f(C)}" r="{f(t["core"] * 0.34)}" fill="{color}"/>')
    theme = "dark" if dark else "light"
    return (header(slug, label, f"{label} composer glyph for {theme} interfaces, transparent ground.")
            + f"<defs>{clip(slug)}{pupil(slug, t['core'] + t['rim'] * 1.6)}</defs>"
            + art_group(slug, "small", color, masked=True) + core + "</svg>\n")


def icon_files(slug: str, label: str) -> dict[str, str]:
    base = f"plugins/icons/{slug}"
    return {
        f"{base}.svg": tile_svg(slug, label, "full"),
        f"{base}-mid.svg": tile_svg(slug, label, "mid"),
        f"{base}-small.svg": tile_svg(slug, label, "small"),
        f"{base}-glyph.svg": glyph_svg(slug, label, dark=False),
        f"{base}-glyph-dark.svg": glyph_svg(slug, label, dark=True),
    }


def png_jobs(slug: str) -> list[tuple[str, str, int]]:
    """(source svg, output png, size) for every raster export of one tool."""
    base = f"plugins/icons/{slug}"
    suffix = {"full": "", "mid": "-mid", "small": "-small"}
    jobs = [(f"{base}{suffix[tier]}.svg", f"plugins/icons/png/{slug}-{size}.png", size)
            for size, tier in PNG_SIZES.items()]
    jobs.append((f"{base}-glyph.svg", f"plugins/icons/png/{slug}-glyph-{GLYPH_PNG}.png", GLYPH_PNG))
    jobs.append((f"{base}-glyph-dark.svg", f"plugins/icons/png/{slug}-glyph-dark-{GLYPH_PNG}.png", GLYPH_PNG))
    return jobs
