"""Render the support, privacy and terms pages for each flagship plugin."""

from __future__ import annotations

import html
import json
import re

from tools import plugin_support_markdown as md
from tools.plugin_support_sources import (
    ToolSource, lead_paragraph, runtime_requirement, sentences_matching, try_it,
)

SITE = "https://harperz9.github.io"
NAV_REV = "20260909-pillar-navigation"
CSS_REV = "20260927-copy-pass"
SERVICE = r"(?i)publisher|telemetry|hosted"
CONTACT = r"^(Contact|Support and security|Report a security)"
STYLE = """<style>
/* Page-scoped: policy lists and subheads at reading size inside the shared chassis. */
.policy-list{max-width:min(100%,58ch);margin:1.2em 0 0;padding-left:1.4em;font-size:clamp(1.05rem,1.3vw,1.18rem);line-height:1.7;color:var(--bone)}
.policy-list li+li{margin-top:.5em}
.mv h3{max-width:min(100%,58ch);margin:2em 0 .6em;font-size:1.05rem;font-weight:600;color:var(--bone)}
.inner-clean .seal{font-size:.875rem;letter-spacing:0;color:var(--muted)}
.plugin-table{width:100%;border-collapse:collapse;font-size:.95rem;color:var(--bone)}
.plugin-table th,.plugin-table td{text-align:left;padding:.6em .8em;border-bottom:1px solid rgba(128,128,128,.3);vertical-align:top}
.plugin-table th[scope=row],.plugin-table td a{white-space:nowrap}
.table-wrap{overflow-x:auto;max-width:72rem;margin:1.6rem auto 0}
</style>"""


def esc(text: str) -> str:
    return html.escape(text, quote=True)


def shell(path: str, title: str, description: str, bar: str, h1: str, main: str, seal: str) -> str:
    url = f"{SITE}/{path}"
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<!-- Generated by tools/build_plugin_support_pages.py from plugins/data. Do not edit. -->
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="{url}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Zain Dana Harper">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="{url}">
<meta name="twitter:card" content="summary">
<meta name="color-scheme" content="dark">
<link rel="stylesheet" href="/system/system.css?v={CSS_REV}">
{STYLE}
</head>
<body class="inner-clean frame-compact">
<a class="skip-link" href="#main">Skip to content</a>

<div id="site-nav" class="site-nav"></div>
<noscript><nav class="site-nav"><a href="/catalog.html">Catalog</a> <a href="/studio.html">The Studio</a> <a href="/overview.html">Flagships</a> <a href="/research.html">Research</a> <a href="/cv.html">About</a></nav></noscript>
<script type="module" src="/system/nav.js?v={NAV_REV}"></script>

<div class="frame">
  <div class="bar"><span class="nm">Zain Dana Harper</span><span class="rt">{bar}</span></div>
  <div class="mid">
    <h1>{h1}</h1>
  </div>
</div>

<main id="main">
{main}
</main>

<footer class="footer-seal" role="contentinfo">
  <p class="seal">{seal}</p>
</footer>
</body>
</html>
"""


def section(anchor: str, heading: str, body: str) -> str:
    return (f'<section class="mv" id="{anchor}" aria-labelledby="{anchor}-h">\n'
            f'  <h2 id="{anchor}-h">{heading}</h2>\n  {body}\n</section>')


def links(tool: ToolSource, current: str) -> str:
    pages = [("support", "Support"), ("privacy", "Privacy policy"), ("terms", "Terms of use")]
    parts = [f'<a href="{key}.html">{label}</a>' for key, label in pages if key != current]
    parts.append(f'<a href="{tool.repo_url}" translate="no">{esc(tool.repo)}</a>')
    parts.append('<a href="../index.html">All plugins</a>')
    return '<div class="channels">' + " &nbsp;&middot;&nbsp; ".join(parts) + "</div>"


def source_note(tool: ToolSource, kind: str, what: str) -> str:
    return (f'<p class="note-line">{what} comes from <a href="{tool.file_url(kind)}" rel="noopener">'
            f'<code translate="no">{esc(tool.sources[kind])}</code></a> in the {esc(tool.label)} repository.</p>')


def slug_anchor(title: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "policy"


def privacy_page(tool: ToolSource) -> str:
    parts = []
    for title, body in md.sections(tool.privacy):
        heading = title or "Policy"
        parts.append(section(slug_anchor(heading), md.inline(heading), md.render(body)))
    parts.append(section("source", "Source", source_note(tool, "privacy", "This policy")
                         + "\n  " + links(tool, "privacy")))
    label = esc(tool.label)
    return shell(f"plugins/{tool.slug}/privacy.html", f"{tool.label} plugin privacy policy",
                 f"What the {tool.label} plugin reads, stores and sends, and how long it keeps data.",
                 f'<span translate="no">{label}</span> &middot; privacy',
                 f"{label} plugin privacy policy", "\n".join(parts),
                 f"{label} plugin &middot; privacy policy from the tool's own repository")


def license_title(text: str) -> str:
    heading = next((line for line in text.splitlines() if line.startswith("# ")), text.splitlines()[0])
    return re.split(r"\s+—\s+", heading.lstrip("# ").strip())[0]


def license_quotes(tool: ToolSource) -> str:
    quote = tool.license_quote
    if "paragraphs" in quote:
        chosen = [b for b in md.blocks(tool.license) if b.startswith(tuple(quote["paragraphs"]))]
        rendered = [md.render_block(b, 3) for b in chosen]
        rendered.append(f'<p class="body-text">{esc(quote["note"])}</p>')
        return "\n  ".join(rendered)
    rendered = []
    for heading in quote["sections"]:
        rendered.append(f"<h3>{esc(heading)}</h3>")
        rendered.append(md.render(md.subsection(tool.license, heading)))
    future = md.blocks(md.subsection(tool.license, quote["future"]))[0]
    first_sentence = re.split(r"(?<=[.])\s+", " ".join(future.split()))[0]
    rendered.append(f"<h3>{esc(quote['future'])}</h3>")
    rendered.append(f'<p class="body-text">{md.inline(first_sentence)}</p>')
    return "\n  ".join(rendered)


def terms_page(tool: ToolSource) -> str:
    label = esc(tool.label)
    title = esc(license_title(tool.license))
    governs = (f'<p class="body-text">{label} has no separate terms-of-service document. The license '
               f'in its repository sets the terms of use: <a href="{tool.file_url("license")}" '
               f'rel="noopener">{title}</a>.</p>')
    service = sentences_matching(tool.privacy, SERVICE)
    if service:
        quoted = " ".join(md.inline(s) for s in service)
        governs += f'\n  <p class="body-text">From the privacy policy: {quoted}</p>'
    parts = [
        section("governs", "What governs use", governs),
        section("license", "License terms", license_quotes(tool)),
        section("source", "Source", source_note(tool, "license", "The license text")
                + "\n  " + links(tool, "terms")),
    ]
    return shell(f"plugins/{tool.slug}/terms.html", f"{tool.label} plugin terms of use",
                 f"The license that governs use of the {tool.label} plugin, quoted from its repository.",
                 f'<span translate="no">{label}</span> &middot; terms',
                 f"{label} plugin terms of use", "\n".join(parts),
                 f"{label} plugin &middot; terms quoted from the tool's own license")


def help_body(tool: ToolSource) -> str:
    issues = f"{tool.repo_url}/issues"
    body = [f'<p class="body-text">Questions and problem reports: <a href="{issues}" rel="noopener">'
            f'<span translate="no">github.com/{esc(tool.repo)}/issues</span></a>.</p>']
    contact = sentences_matching(tool.privacy, CONTACT)
    if contact:
        quoted = " ".join(md.inline(s) for s in contact)
        body.append(f'<p class="body-text">From the privacy policy: {quoted}</p>')
    if tool.has_security:
        body.append(f'<p class="body-text">Security policy: <a href="{tool.file_url("security")}" '
                    f'rel="noopener"><code translate="no">SECURITY.md</code></a>.</p>')
    return "\n  ".join(body)


def support_page(tool: ToolSource) -> str:
    label = esc(tool.label)
    prompts = "".join(f"<li>{md.inline(p)}</li>" for p in try_it(tool.readme))
    install = (f'<p class="body-text">Plugin name: <code translate="no">{esc(tool.manifest["name"])}</code>. '
               f"Runtime: {esc(runtime_requirement(tool.readme))}. The full install steps are in the "
               f'<a href="{tool.file_url("readme")}" rel="noopener">plugin README</a>.</p>')
    parts = [
        section("what", "What it does", f'<p class="body-text">{md.inline(lead_paragraph(tool.readme))}</p>'),
        section("try", "Try it", f'<ul class="policy-list">{prompts}</ul>'),
        section("install", "Before you install", install),
        section("help", "Get help", help_body(tool)),
        section("source", "Source", source_note(tool, "readme", "The text above")
                + "\n  " + links(tool, "support")),
    ]
    return shell(f"plugins/{tool.slug}/support.html", f"{tool.label} plugin support",
                 f"Support for the {tool.label} plugin: what it does, example prompts and where to get help.",
                 f'<span translate="no">{label}</span> &middot; support',
                 f"{label} plugin support", "\n".join(parts),
                 f"{label} plugin &middot; support")


def hub_page(tools: list[ToolSource]) -> str:
    rows = "".join(
        f'<tr><th scope="row" translate="no">{esc(t.label)}</th><td>{esc(t.manifest["description"])}</td>'
        f'<td><a href="{t.slug}/support.html">Support</a> &middot; <a href="{t.slug}/privacy.html">Privacy</a>'
        f' &middot; <a href="{t.slug}/terms.html">Terms</a></td></tr>' for t in tools)
    table = ('<div class="table-wrap"><table class="plugin-table"><thead><tr><th scope="col">Plugin</th>'
             f'<th scope="col">What it does</th><th scope="col">Pages</th></tr></thead><tbody>{rows}</tbody></table></div>')
    intro = ('<p class="body-text">Each flagship tool ships a plugin for local AI clients. These pages give '
             "each plugin's support details, privacy policy and terms of use. Every page quotes the tool's "
             'own repository files. A machine-readable list is at <a href="plugins.json">plugins.json</a>.</p>')
    main = section("plugins", "Plugins", intro + "\n  " + table)
    return shell("plugins/index.html", "Plugin support, privacy and terms",
                 "Support, privacy policy and terms of use pages for each flagship plugin.",
                 "Plugins &middot; support, privacy, terms", "Plugin support, privacy and terms",
                 main, "Plugin pages &middot; text from each tool's own repository")


def index_json(tools: list[ToolSource]) -> str:
    entries = [{
        "tool": t.label, "plugin": t.manifest["name"], "description": t.manifest["description"],
        "repository": t.repo_url,
        "support_url": f"{SITE}/plugins/{t.slug}/support.html",
        "privacy_url": f"{SITE}/plugins/{t.slug}/privacy.html",
        "terms_url": f"{SITE}/plugins/{t.slug}/terms.html",
        "support_contact": f"{t.repo_url}/issues",
    } for t in tools]
    return json.dumps({"schema": "plugin-support-index/1", "plugins": entries}, indent=2) + "\n"


def render_all(tools: list[ToolSource]) -> dict[str, str]:
    files = {"plugins/index.html": hub_page(tools), "plugins/plugins.json": index_json(tools)}
    for tool in tools:
        files[f"plugins/{tool.slug}/support.html"] = support_page(tool)
        files[f"plugins/{tool.slug}/privacy.html"] = privacy_page(tool)
        files[f"plugins/{tool.slug}/terms.html"] = terms_page(tool)
    return files
